on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop
      - master
    types: [closed]
name: ðŸš€ Deploy VPS
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy to Nhut VPS
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v2
    
    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: 116.118.49.192
        username: ${{ secrets.FTP_NHUT_VPS_USER }}
        password: ${{ secrets.FTP_NHUT_VPS_PASS }}
  
  racknerd-deploy:
    name: ðŸŽ‰ Deploy to Racknerd VPS
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v2
    
    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: 107.174.156.33
        username: ${{ secrets.FTP_NHUT_RACKNERD_VPS_USER }}
        password: ${{ secrets.FTP_NHUT_RACKNERD_VPS_PASS }}
